logging:
  level:
    org:
      dbilik:
        fileServer: TRACE

      springframework:
        test: INFO

spring:
  profiles:
    active: mock ,develop

  banner:
    location: classpath:banner.txt